require(dplyr, quietly = TRUE)
require(data.table, quietly = TRUE)
require(reshape2, quietly = TRUE)
require(plyr, quietly = TRUE)
features <- read.table("./UCI HAR Dataset/features.txt")
label <- read.table("./UCI HAR Dataset/activity_labels.txt")
xtest <- read.table("./UCI HAR Dataset/test/X_test.txt", header = FALSE)
ytest <- read.table("./UCI HAR Dataset/test/y_test.txt", header = FALSE)
subject_test <- read.table("./UCI HAR Dataset/test/subject_test.txt", header = FALSE)
names(xtest) <- as.character(features[,2])
ytest <- left_join(ytest, label)
names(ytest) <- c("label", "activity")
names(subject_test) <- "subject"
test_dataset <- bind_cols(list(subject_test, ytest, xtest))
xtrain <- read.table("./UCI HAR Dataset/train/X_train.txt", header = FALSE)
ytrain <- read.table("./UCI HAR Dataset/train/y_train.txt", header = FALSE)
subject_train <- read.table("./UCI HAR Dataset/train/subject_train.txt", header = FALSE)
names(xtrain) <- as.character(features[,2])
ytrain <- left_join(ytrain, label)
names(ytrain) <- c("label", "activity")
names(subject_train) <- "subject"
train_dataset <- bind_cols(list(subject_train, ytrain, xtrain))
full_dataset <- bind_rows(test_dataset,train_dataset)
subset <- select(full_dataset, matches("^subject$|^activity$|mean\\(\\)|std\\(\\)"))
submelt <- melt(subset, names(subset)[1:2], names(subset)[3:68])
submelt <- group_by(submelt, subject, activity, variable)
tidytable <- summarise(submelt, avg = mean(value))
write.table(tidytable, file = "tidydata.csv", row.names = FALSE)